version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: .docker.env
    container_name: recruitment-db
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
